"""CommOCR 用户模版移植数据（04 英文单据 / 05 平面布置 / 06 合同表格）。

由 CommOCR templates.json（2026-09-07 版本）忠实转换：postprocess→hooks、
lenient_fields→lenient、model/skip_text_pdf 保留供级联表单设默认值；
剔除 input_path/output_path/api_key_id/model 等本地字段（model 单独保留）。
id 映射见 scripts/seed_ocr_templates.py。
"""

# 模版→(模版库 id, category, key_name 默认值)
COMMOCR_USER_TEMPLATES = [
    ("ENGLISH_DOC", {
        "source_id": "0f25f6c3",
        "name": "04识别英文单据",
        "model": "qwen-vl-max",
        "skip_text_pdf": True,
        "lenient": False,
        "fields": [
            "记录类型",
            "单据类型",
            "单据编号",
            "单据日期",
            "页数与版本",
            "开具方",
            "开具方联系",
            "接收方",
            "接收方联系",
            "站点编号",
            "站点地址",
            "条目号",
            "工作内容",
            "数量",
            "单位",
            "单价",
            "金额",
            "合计金额",
            "供应商代码",
            "联系人",
            "联系方式",
            "交货地址",
            "开票地址",
            "交货日期",
            "交货条款",
            "付款条款",
            "保修条款",
            "备注",
            "签署说明",
            "签章情况"
        ],
        "prompt_template": "请识别英文商业单据扫描件中的信息，按版式分区还原为多条记录，并严格按照以下要求输出：\n1. 只输出合法的 JSON 数组，不要输出 Markdown 代码块、解释或其他文字。\n2. 每页至少输出 1 条「单据头」记录；版式中存在明细表、供应商块、签章区时，逐块追加对应记录。\n3. 数组中的每条记录必须只包含以下 {field_count} 个字段，字段名必须完全一致：\n   {fields}。\n{rules}\n\n输出结构示例（同页多条记录）：\n{example}",
        "rules": [
            "所有字段值必须照抄纸面可见的原文，原文是英文就原样抄英文，严禁翻译成中文",
            "记录类型只能填 单据头 / 明细行 / 往来方 / 签章 / 照片页 之一，每页第一条记录必须是单据头",
            "单据头记录：承载整页单据级信息——单据类型/单据编号/单据日期/页数与版本/开具方(含联系)/接收方(含联系)/站点编号/站点地址/合计金额/交货日期/交货条款/付款条款/保修条款/备注，其余字段填 未见",
            "单据类型：根据整页版式判断，只能填 INVOICE / PURCHASE ORDER / QUOTATION / WORK COMPLETION FORM / PHOTO PAGE / OTHER 之一",
            "单据编号：发票抄 Invoice No，采购订单抄 Purchase Order No，报价单抄 Quote Ref No，验收表抄表单编号；一页出现多个编号时全部抄录并用分号分隔，保留各自标签（如 PO No: PO202401031013; Quote Ref. No: SHQ/409/28122023）",
            "单据日期照抄原格式（如 10/01/2024、5 Jan 2024、28th December, 2023），不做任何转换或推算；页数与版本抄 Revision No 与 Total Pages（如 Revision No: (blank); Total Page(s): 1/1）",
            "开具方联系/接收方联系：抄公司地址、电话、传真、邮箱（多项用分号连抄，如 Level 20, Tower 1, Kowloon Commerce Centre, No. 51 Kwai Cheong Road, Kwai Chung; Tel: (852) 2945 8000）",
            "明细行记录：明细表（Item No / Product Description / Quantity / Unit Price / Amount 类表）的每一行输出一条记录，填 条目号/工作内容/数量/单位/单价/金额，数量与单位拆开抄（如 3 与 man-day），其余字段填 未见；明细行的工作内容整段照抄，不截断",
            "往来方记录：页面存在供应商信息块（Supplier Code / Contact Person / Tel / Email / Delivery Address / Invoice Address）时输出一条，填 供应商代码/联系人/联系方式/交货地址/开票地址，其余字段填 未见；没有供应商块则不输出此记录",
            "签章记录：页面存在签署区时输出一条——签署说明抄 For and on behalf of 后面的公司名或签署行原文；签章情况描述可见的印章与签名（如 Round company chop + handwritten signature present）；没有签章区则不输出此记录",
            "合计金额：抄明细表 Total 行金额（含货币符号与千分位，如 HKD 2,940.84）；单价与金额照抄数字含货币符号与千分位，无金额填 未见",
            "备注：抄 Remarks 区域全部条目原文（多条编号连抄，如 1) The quotation is valid for 60 days only. 2) Sunday and Public Holidays are not included in work completion calculation.），不截断",
            "整页没有版式字段的（纯照片附页）：只输出一条单据头记录，单据类型填 PHOTO PAGE，备注填 现场照片附页，无文字信息，其余字段填 未见",
            "字段缺失时一律填 未见，禁止编造或推测任何内容"
        ],
        "example": [
            {
                "记录类型": "单据头",
                "单据类型": "PURCHASE ORDER",
                "单据编号": "Purchase Order No: PO202401031013; Quote Ref. No: SHQ/409/28122023",
                "单据日期": "05 Jan 2024",
                "页数与版本": "Revision No: (blank); Total Page(s): 1/1",
                "开具方": "China Mobile Hong Kong Company Limited",
                "开具方联系": "Level 20, Tower 1, Kowloon Commerce Centre, No. 51 Kwai Cheong Road, Kwai Chung; Tel: (852) 2945 8000; Fax: (852) 2845 7747",
                "接收方": "SHEN HUI ENGINEERING (HK) LIMITED",
                "接收方联系": "未见",
                "站点编号": "1503",
                "站点地址": "Roof of Geranium House & Narcissus House, Ma Tau Wai Estate, Kowloon",
                "条目号": "未见",
                "工作内容": "未见",
                "数量": "未见",
                "单位": "未见",
                "单价": "未见",
                "金额": "未见",
                "合计金额": "HKD 2,940.84",
                "供应商代码": "未见",
                "联系人": "未见",
                "联系方式": "未见",
                "交货地址": "未见",
                "开票地址": "未见",
                "交货日期": "On or before 11 Jan 2024",
                "交货条款": "DDP",
                "付款条款": "30 days credit / 70% upon work completion and site on air; 30% upon acceptance by CMHK and document submission",
                "保修条款": "N/A",
                "备注": "1) Please quote our PO number in your invoice and delivery note. 2) If this Order is awarded through a tender process, Supplier shall deliver the Goods or Services in accordance with the compliance response and tender response provided in the tender documents. Relevant tender terms and conditions including the Conditions of Contract shall be binding upon the acceptance of this Order.",
                "签署说明": "未见",
                "签章情况": "未见"
            },
            {
                "记录类型": "明细行",
                "单据类型": "PURCHASE ORDER",
                "单据编号": "Purchase Order No: PO202401031013; Quote Ref. No: SHQ/409/28122023",
                "单据日期": "05 Jan 2024",
                "页数与版本": "未见",
                "开具方": "未见",
                "开具方联系": "未见",
                "接收方": "未见",
                "接收方联系": "未见",
                "站点编号": "未见",
                "站点地址": "未见",
                "条目号": "1",
                "工作内容": "Cell site construction (standard work) Emergency Maintenance for Site 1503",
                "数量": "1",
                "单位": "Job",
                "单价": "HKD 2,940.8400",
                "金额": "HKD 2,940.84",
                "合计金额": "未见",
                "供应商代码": "未见",
                "联系人": "未见",
                "联系方式": "未见",
                "交货地址": "未见",
                "开票地址": "未见",
                "交货日期": "未见",
                "交货条款": "未见",
                "付款条款": "未见",
                "保修条款": "未见",
                "备注": "未见",
                "签署说明": "未见",
                "签章情况": "未见"
            },
            {
                "记录类型": "往来方",
                "单据类型": "PURCHASE ORDER",
                "单据编号": "未见",
                "单据日期": "未见",
                "页数与版本": "未见",
                "开具方": "未见",
                "开具方联系": "未见",
                "接收方": "未见",
                "接收方联系": "未见",
                "站点编号": "未见",
                "站点地址": "未见",
                "条目号": "未见",
                "工作内容": "未见",
                "数量": "未见",
                "单位": "未见",
                "单价": "未见",
                "金额": "未见",
                "合计金额": "未见",
                "供应商代码": "10001939",
                "联系人": "W.Y.LAU, Solar Ho; Nelson WONG Ho Lap",
                "联系方式": "Tel: 9495 2998; Email: shenhui.hk@gmail.com; solar.shenhui.hk@gmail.com; Fax No.: N/A",
                "交货地址": "Roof of Geranium House & Narcissus House, Ma Tau Wai Estate, Kowloon",
                "开票地址": "Level 20, Tower 1, Kowloon Commerce Centre, No.51 Kwai Cheong Road, Kwai Chung (Attn: Finance Dept.)",
                "交货日期": "未见",
                "交货条款": "未见",
                "付款条款": "未见",
                "保修条款": "未见",
                "备注": "未见",
                "签署说明": "未见",
                "签章情况": "未见"
            },
            {
                "记录类型": "签章",
                "单据类型": "PURCHASE ORDER",
                "单据编号": "未见",
                "单据日期": "未见",
                "页数与版本": "未见",
                "开具方": "未见",
                "开具方联系": "未见",
                "接收方": "未见",
                "接收方联系": "未见",
                "站点编号": "未见",
                "站点地址": "未见",
                "条目号": "未见",
                "工作内容": "未见",
                "数量": "未见",
                "单位": "未见",
                "单价": "未见",
                "金额": "未见",
                "合计金额": "未见",
                "供应商代码": "未见",
                "联系人": "未见",
                "联系方式": "未见",
                "交货地址": "未见",
                "开票地址": "未见",
                "交货日期": "未见",
                "交货条款": "未见",
                "付款条款": "未见",
                "保修条款": "未见",
                "备注": "未见",
                "签署说明": "For and on behalf of China Mobile Hong Kong Company Limited",
                "签章情况": "Round company chop (CHINA MOBILE HONG KONG COMPANY LIMITED) + handwritten signature over Company Chop & Authorized Signature line"
            }
        ],
        "postprocess": [
            {
                "name": "类型规范化",
                "code": "def transform_page(records, ctx):\n    \"\"\"记录类型与单据类型规范化：白名单归一 + 关键词模糊映射。\"\"\"\n    rtypes = {'单据头', '明细行', '往来方', '签章', '照片页'}\n    dtypes = {'INVOICE', 'PURCHASE ORDER', 'QUOTATION',\n              'WORK COMPLETION FORM', 'PHOTO PAGE', 'OTHER'}\n    fixed = 0\n\n    def norm_rtype(v):\n        s = (v or '').strip()\n        u = s.upper()\n        if s in rtypes:\n            return s\n        if not s:\n            return '单据头'\n        if '明细' in s or 'ITEM' in u:\n            return '明细行'\n        if '供应' in s or 'SUPPLIER' in u:\n            return '往来方'\n        if '签' in s or 'SIGN' in u or 'CHOP' in u:\n            return '签章'\n        if '照片' in s or 'PHOTO' in u:\n            return '照片页'\n        return '单据头'\n\n    def norm_dtype(v):\n        u = (v or '').strip().upper()\n        if not u:\n            return 'OTHER'\n        if u in dtypes:\n            return u\n        if 'INVOICE' in u:\n            return 'INVOICE'\n        if 'PURCHASE' in u or u == 'PO':\n            return 'PURCHASE ORDER'\n        if 'QUOT' in u:\n            return 'QUOTATION'\n        if 'COMPLETION' in u or 'WCF' in u:\n            return 'WORK COMPLETION FORM'\n        if 'PHOTO' in u or 'PICTURE' in u or 'IMAGE' in u:\n            return 'PHOTO PAGE'\n        return 'OTHER'\n\n    for r in records:\n        rt = (r.get('记录类型') or '').strip()\n        nrt = norm_rtype(rt)\n        if rt != nrt:\n            r['记录类型'] = nrt\n            fixed += 1\n        d = (r.get('单据类型') or '').strip()\n        nd = norm_dtype(d)\n        if d != nd:\n            r['单据类型'] = nd\n            fixed += 1\n    if fixed:\n        ctx['review']('类型规范化处理 ' + str(fixed) + ' 处')\n    return records"
            },
            {
                "name": "明细行继承单据头",
                "code": "def transform_page(records, ctx):\n    \"\"\"明细行/往来方/签章记录继承单据头的单据类型、单据编号、单据日期（同页冗余，便于单行独立阅读）。\n    单据类型空或 OTHER（未识别）同样继承——同页单据类型必然一致。\"\"\"\n    head = next((r for r in records if (r.get('记录类型') or '') == '单据头'), None)\n    if not head:\n        return records\n    inherited = 0\n    for r in records:\n        if r is head:\n            continue\n        for k in ('单据类型', '单据编号', '单据日期'):\n            empty = r.get(k) in (None, '', '未见') or (k == '单据类型' and r.get(k) == 'OTHER')\n            if empty and (head.get(k) or '') not in ('', '未见', 'OTHER'):\n                r[k] = head[k]\n                inherited += 1\n    if inherited:\n        ctx['review']('明细记录继承单据头字段 ' + str(inherited) + ' 处')\n    return records"
            },
            {
                "name": "空值兜底填未见",
                "code": "def transform_page(records, ctx):\n    \"\"\"空值兜底：空值（None/空串）统一填「未见」。\"\"\"\n    filled = 0\n    for r in records:\n        for k, v in r.items():\n            if v is None or (isinstance(v, str) and not v.strip()):\n                r[k] = '未见'\n                filled += 1\n    if filled:\n        ctx['review']('空值兜底填「未见」' + str(filled) + ' 处')\n    return records"
            }
        ]
    }),
    ("BLUEPRINT", {
        "source_id": "6f9a29a1",
        "name": "05识别平面布置",
        "model": None,
        "skip_text_pdf": False,
        "lenient": True,
        "fields": [
            "记录类型",
            "图纸名称",
            "图号",
            "公司负责人",
            "日期",
            "说明内容",
            "印章遮挡",
            "表格名称",
            "序号",
            "名称",
            "规格型号",
            "配置",
            "厂家",
            "单位",
            "数量",
            "备注"
        ],
        "prompt_template": "请识别这页通信基站设计图（平面布置图/示意图），并严格按照以下要求输出：\n1. 只输出合法的 JSON 数组，不要输出 Markdown 代码块、解释或其他文字。\n2. 数组中的每条记录必须只包含以下 {field_count} 个字段，字段名必须完全一致：\n   {fields}。\n{rules}\n\n输出结构示例：\n{example}",
        "rules": [
            "- 【通用结构】每页先输出恰好 1 条主记录（平面图页\"记录类型\"=\"图纸信息\"，风险提示页\"记录类型\"=\"风险提示页\"，判定见【风险提示页】条），再按页面出现顺序逐行输出\"记录类型\"=\"表格行\"和/或\"风险提示\"的记录。所有字段值都必须是字符串；某记录类型不适用的字段一律填空字符串 \"\"（如表格行的\"图纸名称\"填 \"\"），严禁填\"未见\"\"无\"等字样；\"印章遮挡\"仅主记录（图纸信息/风险提示页）适用，表格行与风险提示条目一律填 \"\"。",
            "- 【标题栏（页面右下角图签表）】按标签与填写格的物理位置对齐取值：\"图纸名称\"填图签上方的大字图名，图名常分两行（第一行工程名如\"泸沽蓝星\"、第二行图名如\"物资材料表\"），此时两行拼接为一行，中间不留空格（\"泸沽蓝星物资材料表\"）；单行图名则照抄。\"图号\"填图签\"图号\"行的值（如 WX1500XX-泸沽蓝星-01）；\"公司负责人\"只填\"公司负责人\"标签对应格内的值（常为空，空则填 \"\"）：先在图签中找到文字\"公司负责人\"，只取其正右方或正下方紧邻格的值；若手写签名（如\"彭渝\"）物理对齐的是\"单项负责人\"\"设计人\"\"制（描）图\"等其他标签，严禁填入\"公司负责人\"，此时留空。\"日期\"填图签\"日期\"行的值（如 2015.03），照抄原格式。图签中的\"阶段\"\"单位/比例\"\"一/二/三审\"等其他行不要提取。",
            "- 【说明内容】页面中由\"说明：\"\"注：\"\"图例\"引导的全部文字（含编号条目 1. 2. 3.）逐字照抄、保留原编号，多段按出现顺序用\" ‖ \"分隔合并进\"说明内容\"字段。图形区内的尺寸标注数字、指北针、坐标经纬度单独标签不属于说明；但说明条目内部提到的经纬度/海拔照抄。说明常紧邻图形，注意不要漏抄段落较长的第 3、4 条。严禁改写、缩写或总结。 风险提示页的条目正文不并入说明内容（拆到\"风险提示\"条目记录），风险提示页主记录的说明内容填 \"\"。",
            "- 【风险提示页】页面没有平面布置图、主体为中文序数编号的条目列表（如\"一、一般规定\"\"十二、工程防火安全\"）时，判定为风险提示页：主记录\"记录类型\"=\"风险提示页\"（图纸名称/图号/公司负责人/日期照常从图签取，说明内容填 \"\"），并按出现顺序每条条目输出一条\"记录类型\"=\"风险提示\"的记录：\"序号\"填中文序数（如\"一\"\"十二\"），\"名称\"填条目标题（如\"一般规定\"），\"说明内容\"填该条目全部正文（含 1. 2. 3. 子条目，逐字照抄），其余字段填 \"\"。条目跨页时各自输出本页的条目。",
            "- 【附加表格】页面上除右下角图签外的数据表格（如\"设备列表\"\"基站新增物资表\"\"基站新增塔桅及塔桅构件表\"\"物资材料表\"），每一条数据行输出一条\"表格行\"记录：\"表格名称\"填表格标题原文并去掉字间空格（\"设 备 列 表\"→\"设备列表\"）；列对应关系：序号→\"序号\"；\"设备名称\"/\"塔桅及塔桅构件名称\"等名称列→\"名称\"；\"设备尺寸(W*D*H)\"/\"规格型号\"/\"设备型号\"等型号尺寸列→\"规格型号\"；\"配置\"列（含组成描述的长文字）→\"配置\"；\"厂家\"→\"厂家\"；\"单位\"→\"单位\"；\"数量\"→\"数量\"（只填数字，若原表数量与单位连写如\"1架\"则拆分：数量填\"1\"、单位填\"架\"）；\"备注\"→\"备注\"。表格没有的列填 \"\"。合并单元格的值对下方各行重复照抄。单元格长文字（如配置描述）完整照抄不断句删减。表格标题若无、仅有序列表格，\"表格名称\"填 \"\"。",
            "- 【严禁混淆】右下角图签表（公司负责人/单项负责人/设计人/日期/阶段/单位比例/图号）不是附加表格，严禁输出为表格行记录；图形区标注文字不是说明也不是表格。",
            "- 【印章遮挡判定】仅针对主记录（图纸信息/风险提示页）：只判断印章是否直接覆盖所需内容并导致文字无法辨认或内容缺失，所需内容=说明文字段、风险提示条目正文、正文数据表格三类（图签四格——图纸名称/图号/公司负责人/日期——与其他任何区域被压均不算）。以下一律不算：印章压图签表任何位置（含审核签字栏一审/二审/三审/阶段）；压图形区、图例、空白处；虽压住文字但文字仍清晰可辨（如红色半透明章下黑字可读）。确认覆盖致缺失才标记：\"遮挡说明\"（说明文字/风险提示正文被压缺失）、\"遮挡表格\"（表格数据被压缺失）；两项同时发生填\"遮挡说明+遮挡表格\"；其余一律\"无\"。宁可漏报不可误报，判不准时填\"无\"。",
            "- \"备注\"字段：某字段识别不确定、字迹或线条模糊、疑似串行时简要说明（如\"数量模糊\"）；表格行该行区域被红色印章压住时，追加\"；被印章遮挡\"；多项用\"；\"分隔；全部正常填 \"\"。"
        ],
        "example": [
            {
                "记录类型": "图纸信息",
                "图纸名称": "泸沽蓝星总体平面布置图",
                "图号": "WX1500XX-泸沽蓝星-01",
                "公司负责人": "",
                "日期": "2015.03",
                "说明内容": "说明： 1.本次工程位于凉山冕宁泸沽蓝星。基站地址:泸沽胜利村小学斜对面,共享联通胜利基站。 2.基站安装位置经纬度: N28.19753°/ E102.12041°,海拔1688m。 3.本基站市电引入容量不小于20 KVA。",
                "表格名称": "",
                "序号": "",
                "名称": "",
                "规格型号": "",
                "配置": "",
                "厂家": "",
                "单位": "",
                "数量": "",
                "备注": "",
                "印章遮挡": "无"
            },
            {
                "记录类型": "表格行",
                "图纸名称": "",
                "图号": "",
                "公司负责人": "",
                "日期": "",
                "说明内容": "",
                "表格名称": "设备列表",
                "序号": "1",
                "名称": "电源综合柜",
                "规格型号": "905*905*2000",
                "配置": "含交流配电单元、嵌入式开关电源、接地汇流排,2组150AH蓄电池",
                "厂家": "",
                "单位": "架",
                "数量": "1",
                "备注": "新增设备",
                "印章遮挡": ""
            },
            {
                "记录类型": "表格行",
                "图纸名称": "",
                "图号": "",
                "公司负责人": "",
                "日期": "",
                "说明内容": "",
                "表格名称": "设备列表",
                "序号": "2",
                "名称": "走线架",
                "规格型号": "400mm宽",
                "配置": "",
                "厂家": "",
                "单位": "米",
                "数量": "5",
                "备注": "",
                "印章遮挡": ""
            },
            {
                "记录类型": "风险提示页",
                "图纸名称": "中国铁塔股份有限公司凉山州分公司2023年凉山金阳河东新区铁塔配套工程",
                "图号": "WX230001-凉山金阳河东新区铁塔-01",
                "公司负责人": "邱泽华",
                "日期": "2023.07",
                "说明内容": "",
                "印章遮挡": "无",
                "表格名称": "",
                "序号": "",
                "名称": "",
                "规格型号": "",
                "配置": "",
                "厂家": "",
                "单位": "",
                "数量": "",
                "备注": ""
            },
            {
                "记录类型": "风险提示",
                "图纸名称": "",
                "图号": "",
                "公司负责人": "",
                "日期": "",
                "说明内容": "一、一般规定\n1. 工程建设必须按照国家关于安全生产的法律、法规和工程建设强制性标准遵守国家相关安全生产法律、法规的规定，保证建设工程安全生产，依法承担建设工程安全生产责任。\n2. 施工单位应设置安全生产管理机构并配备专职安全生产管理人员。\n3. 工程项目施工应实行安全技术交底制度，接受交底的人员应覆盖全体作业人员。安全技术交底应包括以下主要内容：\n（1） 工程项目的施工作业特点和危险因素；\n（2） 针对危险因素制定的具体预防措施；\n（3） 相应的安全生产操作规程和标准；\n（4） 在施生产中应注意的安全事项；\n（5） 发生事故后应采取的应急措施。\n4. 施工人员应正确穿戴和使用符合国家或行业质量标准的劳动防护用品、工具。",
                "印章遮挡": "",
                "表格名称": "",
                "序号": "一",
                "名称": "一般规定",
                "规格型号": "",
                "配置": "",
                "厂家": "",
                "单位": "",
                "数量": "",
                "备注": ""
            },
            {
                "记录类型": "风险提示",
                "图纸名称": "",
                "图号": "",
                "公司负责人": "",
                "日期": "",
                "说明内容": "1. 施工现场应设置明显的安全警示标志，施工人员必须佩戴安全帽。",
                "印章遮挡": "",
                "表格名称": "",
                "序号": "二",
                "名称": "施工现场安全",
                "规格型号": "",
                "配置": "",
                "厂家": "",
                "单位": "",
                "数量": "",
                "备注": ""
            }
        ],
        "postprocess": [
            {
                "name": "表格名称规范化",
                "code": "def transform_page(records, ctx):\n    \"\"\"表格名称去空白（全/半角）+ 全字段首尾 trim，标题对齐利于跨文件续写。\"\"\"\n    fixed = 0\n    for r in records:\n        for k, v in r.items():\n            if isinstance(v, str) and v != v.strip():\n                r[k] = v.strip()\n        name = r.get('表格名称') or ''\n        if name:\n            cleaned = re.sub(r'[\\s\\u3000]+', '', name)\n            if cleaned != name:\n                r['表格名称'] = cleaned\n                fixed += 1\n    if fixed:\n        ctx['review']('表格名称去空格规范化 ' + str(fixed) + ' 处')\n    return records"
            },
            {
                "name": "主记录唯一性兜底",
                "code": "def transform_page(records, ctx):\n    \"\"\"每页主记录（图纸信息/风险提示页）应恰 1 条：多条保留首条并报告；零条仅报告不补造。\"\"\"\n    info = [r for r in records if r.get('记录类型') in ('图纸信息', '风险提示页')]\n    if len(info) > 1:\n        drop = info[1:]\n        for r in drop:\n            records.remove(r)\n        ctx['review']('主记录重复 ' + str(len(drop)) + ' 条，已保留首条')\n    elif len(info) == 0:\n        ctx['review']('本页缺主记录（未补造，注意核对）')\n    return records"
            },
            {
                "name": "印章遮挡规整",
                "code": "def transform_page(records, ctx):\n    \"\"\"印章遮挡枚举规整：非法值并入合法值域；历史值\"遮挡图签\"已废弃→归并为\"无\"。\"\"\"\n    ALLOWED = {'无', '遮挡说明', '遮挡表格', '遮挡说明+遮挡表格'}\n    for r in records:\n        v = (r.get('印章遮挡') or '').strip()\n        if not v:\n            continue\n        if '遮挡图签' in v:\n            rest = [p for p in v.split('+') if p != '遮挡图签']\n            v = '+'.join(rest) if rest else '无'\n        if v not in ALLOWED:\n            ctx['review']('印章遮挡非法值 ' + repr(v) + '，已归并为 无')\n            v = '无'\n        r['印章遮挡'] = v\n    return records"
            },
            {
                "name": "印章遮挡传播",
                "code": "def transform_page(records, ctx):\n    \"\"\"页级\"遮挡表格\"传播到行：整页表格行备注追加\"；被印章遮挡\"（人工按页回查）。\"\"\"\n    info = [r for r in records if r.get('记录类型') == '图纸信息']\n    if not info or '遮挡表格' not in (info[0].get('印章遮挡') or ''):\n        return records\n    n = 0\n    for r in records:\n        if r.get('记录类型') != '表格行':\n            continue\n        note = r.get('备注') or ''\n        if '被印章遮挡' not in note:\n            r['备注'] = (note + '；被印章遮挡') if note else '被印章遮挡'\n            n += 1\n    if n:\n        ctx['review']('印章遮挡传播至表格行 ' + str(n) + ' 条')\n    return records"
            },
            {
                "name": "风险提示正文规整",
                "code": "def transform_page(records, ctx):\n    \"\"\"风险提示记录正文首行若恰为\"序号、名称\"标题行则剥除（名称字段已承载标题）。\"\"\"\n    for r in records:\n        if r.get('记录类型') != '风险提示':\n            continue\n        head = (str(r.get('序号')) + '、' + str(r.get('名称'))).strip()\n        body = (r.get('说明内容') or '').lstrip('\\n')\n        if head and body.startswith(head):\n            r['说明内容'] = body[len(head):].lstrip('\\n')\n    return records"
            }
        ]
    }),
    ("CONTRACT_TABLE", {
        "source_id": "93cb0ee6",
        "name": "06合同表格识别",
        "model": None,
        "skip_text_pdf": False,
        "lenient": True,
        "fields": [
            "合同类型",
            "日期",
            "采购单号",
            "甲方合同编号",
            "序号",
            "名称",
            "规格型号",
            "单位",
            "数量",
            "单价",
            "金额",
            "备注"
        ],
        "prompt_template": "请识别这页合同（采购合同 / 产品采购加工合同），并严格按照以下要求输出：\n1. 只输出合法的 JSON 数组，不要输出 Markdown 代码块、解释或其他文字。\n2. 数组中的每条记录必须只包含以下 {field_count} 个字段，字段名必须完全一致：\n   {fields}。\n{rules}\n\n输出结构示例：\n{example}",
        "rules": [
            "- 【通用结构】每页为一份合同，页内表格的每一条数据行（含末尾合计行）输出一条记录；「合同类型」「日期」「采购单号」「甲方合同编号」四个合同级字段在本页每条记录上重复填写同一值。所有字段值必须是字符串；不适用的字段一律填空字符串 \"\"，严禁填\"未见\"\"无\"\"N/A\"等字样。",
            "- 【合同类型判定】页面右上角有\"采购单号\"字样 → \"采购合同\"；页面右上角有\"甲方合同编号\"、且正文有\"一、产品名称、型号、单位、数量、单价及金额\"条款 → \"产品采购加工合同\"。该字段只允许这两个值之一，不要输出其他写法。",
            "- 【采购合同页】\"日期\"填页面中间偏上位置所写的日期，逐字照抄原格式（如 2021-12-8 或 2021年11月12日，不要改写统一）；\"采购单号\"填页面右上角采购单号全串照抄；\"甲方合同编号\"填 \"\"。",
            "- 【产品采购/加工合同页】\"甲方合同编号\"填页面右上角\"甲方合同编号\"标签处的编号全串照抄；\"日期\"与\"采购单号\"填 \"\"。",
            "- 【表格列映射】表格数据行逐列对应：序号→\"序号\"；产品名称/物料名称/品名/货物名称/设备名称等名称列→\"名称\"；型号/规格/规格型号等列→\"规格型号\"；单位→\"单位\"；数量→\"数量\"（只填数字）；单价→\"单价\"（只填数字，可含小数点）；金额→\"金额\"（只填数字）。原表没有的列填 \"\"。数量与单位连写时拆分（如\"3批\"→数量\"3\"、单位\"批\"）。",
            "- 【合计行】表格末尾的\"合计\"行也输出一条记录：\"名称\"填\"合计\"，合计行中有值的列照抄（如金额、数量），其余列填 \"\"。",
            "- 【合并单元格】合并单元格的值对其下方各行重复照抄。",
            "- 【并集外列】表格出现上述字段容纳不了的列（如税率、交货日期、品牌等），将该列每一行的值以\"列名:值\"写入\"备注\"，多项用\"；\"分隔；无则\"备注\"填 \"\"。字迹模糊、印章遮挡或疑似串行时，也在\"备注\"简要注明。",
            "- 【照抄原则】只照抄纸面可见内容，严禁推断、补全、换算金额、改写日期格式；示例中的编号、名称、数值仅为格式示意，实际一律以纸面为准。",
            "- 【界限】落款签字区、合同条款正文、骑缝章文字都不是表格行，严禁输出为记录；每页只输出表格数据行。"
        ],
        "example": [
            {
                "合同类型": "采购合同",
                "日期": "2021-12-8",
                "采购单号": "CG2021-1208-01",
                "甲方合同编号": "",
                "序号": "1",
                "名称": "复印纸",
                "规格型号": "A4 70g",
                "单位": "箱",
                "数量": "10",
                "单价": "120",
                "金额": "1200",
                "备注": ""
            },
            {
                "合同类型": "采购合同",
                "日期": "2021-12-8",
                "采购单号": "CG2021-1208-01",
                "甲方合同编号": "",
                "序号": "",
                "名称": "合计",
                "规格型号": "",
                "单位": "",
                "数量": "10",
                "单价": "",
                "金额": "1200",
                "备注": ""
            },
            {
                "合同类型": "产品采购加工合同",
                "日期": "",
                "采购单号": "",
                "甲方合同编号": "ZTH-CG-2021-25",
                "序号": "1",
                "名称": "不锈钢支架",
                "规格型号": "JX-300",
                "单位": "件",
                "数量": "50",
                "单价": "85.5",
                "金额": "4275",
                "备注": "交货日期:2021-12-30"
            }
        ],
        "postprocess": [
            {
                "name": "字段与类型规整",
                "code": "def transform_page(records, ctx):\n    \"\"\"全字段 trim；合同类型白名单归一（去空白/近似写法映射到两个标准值）。\"\"\"\n    CANON = {\"采购合同\", \"产品采购加工合同\"}\n    fixed = 0\n    for r in records:\n        for k, v in r.items():\n            if isinstance(v, str) and v != v.strip():\n                r[k] = v.strip()\n                fixed += 1\n        t = re.sub(r\"[\\s\\u3000]+\", \"\", r.get(\"合同类型\") or \"\")\n        if t and t not in CANON:\n            new = \"产品采购加工合同\" if (\"产品\" in t or \"加工\" in t) else (\"采购合同\" if \"采购\" in t else \"\")\n            if new:\n                r[\"合同类型\"] = new\n                fixed += 1\n            else:\n                ctx[\"review\"](\"合同类型无法归一：\" + t)\n        elif t in CANON and t != r.get(\"合同类型\"):\n            r[\"合同类型\"] = t\n            fixed += 1\n    n_empty = sum(1 for r in records if not (r.get(\"合同类型\") or \"\").strip())\n    if n_empty:\n        ctx[\"review\"](\"本页 \" + str(n_empty) + \" 条记录合同类型为空（未强行归一）\")\n    if fixed:\n        ctx[\"review\"](\"字段/类型规整 \" + str(fixed) + \" 处\")\n    return records"
            },
            {
                "name": "合同级字段行间传播",
                "code": "def transform_page(records, ctx):\n    \"\"\"合同级字段（日期/采购单号/甲方合同编号）行间兜底：空值行继承本页首个非空值；整页缺失发核对提示。\"\"\"\n    if not records:\n        return records\n    level_fields = [\"日期\", \"采购单号\", \"甲方合同编号\"]\n    filled = 0\n    for f in level_fields:\n        src = \"\"\n        for r in records:\n            v = (r.get(f) or \"\").strip()\n            if v:\n                src = v\n                break\n        if not src:\n            continue\n        for r in records:\n            if not (r.get(f) or \"\").strip():\n                r[f] = src\n                filled += 1\n    if filled:\n        ctx[\"review\"](\"合同级字段行间补齐 \" + str(filled) + \" 处\")\n    kind = (records[0].get(\"合同类型\") or \"\").strip()\n    required = (\"日期\", \"采购单号\") if kind == \"采购合同\" else (\"甲方合同编号\",) if kind == \"产品采购加工合同\" else ()\n    for f in required:\n        if not any((r.get(f) or \"\").strip() for r in records):\n            ctx[\"review\"](\"本页「\" + f + \"」整页为空，请核对原件\")\n    return records"
            },
            {
                "name": "数值规整",
                "code": "def transform_page(records, ctx):\n    \"\"\"数量/单价/金额：去货币符号与千分位（仅当清理后为纯数字时才落笔，其余原样保留）。\"\"\"\n    num_re = re.compile(r\"^-?\\d+(?:\\.\\d+)?$\")\n    fixed = 0\n    for r in records:\n        for f in (\"数量\", \"单价\", \"金额\"):\n            v = (r.get(f) or \"\").strip()\n            if not v:\n                continue\n            c = v.replace(\"￥\", \"\").replace(\"¥\", \"\").replace(\",\", \"\").replace(\"，\", \"\")\n            c = c.replace(\" \", \"\").replace(\"\\u3000\", \"\")\n            if c.endswith(\"元\"):\n                c = c[:-1]\n            if c != v and num_re.match(c):\n                r[f] = c\n                fixed += 1\n    if fixed:\n        ctx[\"review\"](\"数值规整 \" + str(fixed) + \" 处\")\n    return records"
            }
        ]
    }),
]
